### ISSUE TITLE
does sleep/awake work with yout EFI?

### ISSUE THREAD

**Issue by Kaijun** [haxgun/Ryzentosh#4]
how do you tweak your config to make sleep/awake work?

i've done usb mapping and bios setting, but the build can't even go deep sleep and can't be waken.

**Comment by MAGICXcmd** [comment]
@Kaijun Good afternoon!

Sleep/awake works fine. I use it daily.
All I did was [set up the BIOS ](https://github.com/MAGICXcmd/Ryzentosh/tree/main#-bios) and did [USB mapping](https://github.com/MAGICXcmd/Ryzentosh/blob/main/EFI/OC/ACPI/SSDT-EC-USBX-DESKTOP.aml).

Do you use iGPU (NootedRed) or dGPU (WhateverGreen)? If dGPU, which dGPU do you have?

**Comment by Kaijun** [comment]
@MAGICXcmd 

Thank you for your advice. I'm happy to report that the sleep and awake functions are now working after making some adjustments in the BIOS. Specifically, disabling `IOMMU` did the trick.

By the way, my build has a R5-5600G CPU and an dGPU (RX580). 

I've noticed that I also need to add the -wegnoigpu flag to disable the iGPU. It appears that the iGPU might be causing issues with the sleep function.
